NPM workflow debug

diff --git a/.github/workflows/build-npm-packages.yml b/.github/workflows/build-npm-packages.yml
--- a/.github/workflows/build-npm-packages.yml
+++ b/.github/workflows/build-npm-packages.yml
@@ -68,22 +68,26 @@ jobs:
                    "$SLICE2JS_STAGING_PATH/windows-x64"
 
           # Copy the slice2js binaries to the staging path.
-          cp artifacts/slice2js-macos-arm64/slice2js "$SLICE2JS_STAGING_PATH/macos-arm64/"
-          cp artifacts/slice2js-linux-x64/slice2js "$SLICE2JS_STAGING_PATH/linux-x64/"
-          cp artifacts/slice2js-linux-arm64/slice2js "$SLICE2JS_STAGING_PATH/linux-arm64/"
-          cp artifacts/slice2js-windows-x64/slice2js.exe "$SLICE2JS_STAGING_PATH/windows-x64/"
+          cp -v artifacts/slice2js-macos-arm64/slice2js "$SLICE2JS_STAGING_PATH/macos-arm64/"
+          cp -v artifacts/slice2js-linux-x64/slice2js "$SLICE2JS_STAGING_PATH/linux-x64/"
+          cp -v artifacts/slice2js-linux-arm64/slice2js "$SLICE2JS_STAGING_PATH/linux-arm64/"
+          cp -v artifacts/slice2js-windows-x64/slice2js.exe "$SLICE2JS_STAGING_PATH/windows-x64/"
 
           # Copy the slice2js binary to the cpp/bin directory to avoid rebuilding it.
           mkdir -p ice/cpp/bin
-          cp artifacts/slice2js-linux-x64/slice2js $GITHUB_WORKSPACE/ice/cpp/bin/slice2js
-          ls $GITHUB_WORKSPACE/ice/cpp/bin
+          cp -v artifacts/slice2js-linux-x64/slice2js $GITHUB_WORKSPACE/ice/cpp/bin/slice2js
 
       - name: Build JS
         run: make
         working-directory: ice/js
 
       - name: Pack npm
-        run: npm pack
+        run: |
+          if [ ! -f "$GITHUB_WORKSPACE/ice/cpp/bin/slice2js" ]; then
+            echo "Error: slice2js binary is missing in cpp/bin"
+            exit 1
+          fi
+          npm pack
         working-directory: ice/js
 
       - name: Upload NPM Packages
